spring.application.name=school
server.port=8080
spring.datasource.url= jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username= student
spring.datasource.password= chocolatefrog
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.jpa.hibernate.ddl-auto=validate
path.to.avatars.folder= /avatars
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml